name: "Check Licenses"
description: "Checks project dependencies for license compliance"

inputs:
  project_license:
    description: "Project License"
    required: true
  working_directory:
    description: "Working directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install LicenseFinder
      run: |
        sudo gem install license_finder
      shell: bash
    
    - name: Run LicenseFinder
      run: |
        echo "🔎 Running LicenseFinder in working directory: '${{ inputs.working_directory }}', for license: '${{ inputs.project_license }}'"

        HEAD_POLICY_FILE="$GITHUB_ACTION_PATH/doc/${{ inputs.project_license }}/dependency_decisions.yml"

        if [ ! -f "$HEAD_POLICY_FILE" ]; then
          echo "❌ Head Policy-file for license '${{ inputs.project_license }}' not found."
          exit 1
        else
          echo "📝 Head Policy-file"
          cat "$HEAD_POLICY_FILE"

          license_finder inherited_decisions add "$HEAD_POLICY_FILE"
        fi

        LOCAL_POLICY_FILE="${{ inputs.working_directory }}/doc/dependency_decisions.yml"

        cd "${{ inputs.working_directory }}"

        if [ ! -f "$LOCAL_POLICY_FILE" ]; then
          echo "ℹ️ No local Policy-file found."
          
          license_finder
        else
          echo "ℹ️ Found local Policy-file."
          echo "📝 Local Policy-file"
          cat "$LOCAL_POLICY_FILE"
          
          license_finder --decisions-file "$LOCAL_POLICY_FILE"
        fi

      shell: bash
